spring:
  application:
    name: ms-config
  profiles:
    active: dev
  cloud:
      config:
        server:
          git:
            uri: https://github.com/luohoufa/springcloudstudy.git
            search-paths: config-repo
            username:
            password:
        label: master
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
